---
repositories:
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts
  - name: sstarcher 
    url: https://shanestarcher.com/helm-charts/
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: gatekeeper
    url: https://open-policy-agent.github.io/gatekeeper/charts

releases:

  - name: gatekeeper
    chart: gatekeeper/gatekeeper
    namespace: gatekeeper
    version: "3.8.1"
    createNamespace: true 
    installed: true 

  - name: vault
    chart: hashicorp/vault
    namespace: vault
    version: "0.19.0"
    createNamespace: true 
    installed: true
    values:
      - injector.enabled: true

  - name: helm-exporter 
    chart: sstarcher/helm-exporter
    namespace: helm-exporter
    version: "1.2.2+6766a95"
    createNamespace: true 
    installed: true

  - name: promstack
    chart: prometheus-community/kube-prometheus-stack
    namespace: promstack
    version: "35.0.3"
    createNamespace: true 
    installed: true 
    values:

